site_name: 1st Task;)
site_description: Практикум 1. Настройка среды Docs as Code
theme:
  name: material
  custom_dir: overrides
  language: ru
  font: false
  palette:
    scheme: slate
    primary:  black
    accent: white
  icon:
    logo: material/book-open-page-variant
  features:
    - navigation.top
    - search.highlight
    - content.code.copy
nav:
  - Главная: index.md
plugins:
  - search:
      lang: ru
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/reveal.js
extra:
  generator: false
copyright: Основы технического документирования · Практикум 1
